### ISSUE TITLE
Not working in 0.20

### ISSUE THREAD

**Issue by pedrodevoto** [bulenttastan/react-native-list-popover#15]
It is not working in my 0.20 installation and I can't seem to figure out why. Have you guys tested it in the latest version?

It is not a problem with naming collisions, it just wont show up when setting the isVisible prop.

**Comment by niftylettuce** [comment]
I get a naming collision in 0.20.x:

``` log
Failed to build DependencyGraph: Naming collision detected: /Users/nexus/Public/MyProject/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js collides with /Users/nexus/Public/MyProject/node_modules/react-native-list-popover/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js
Error: Naming collision detected: /Users/nexus/Public/MyProject/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js collides with /Users/nexus/Public/MyProject/node_modules/react-native-list-popover/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
    at tryCallOne (/Users/nexus/Public/MyProject/node_modules/promise/lib/core.js:37:12)
    at /Users/nexus/Public/MyProject/node_modules/promise/lib/core.js:123:15
    at flush (/Users/nexus/Public/MyProject/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
```

**Comment by niftylettuce** [comment]
Per #10 and this issue, #15, you can resolve by removing this package from your project and node_modules folder, and then installing it manually through GitHub with `npm install --save bulenttastan/react-native-list-popover`.  The reason this fails is because the version in NPM is different than the version in this repo/master branch (the differences are in the package.json files, one has `dependencies` and the other doesn't; the NPM one has `react-native: 0.4.0` specified when it shouldn't have any deps).

**Comment by niftylettuce** [comment]
@bulenttastan Please run `npm publish` on this project!

**Comment by niftylettuce** [comment]
Another possible fix may be to install NPM v3 locally.

**Comment by niftylettuce** [comment]
1.0.4 needs released basically to NPM

**Comment by niftylettuce** [comment]
I also reproduced this issue now that the package installs.  It still does not work with isVisible=true.

**Comment by bulenttastan** [comment]
Bumped the version and published to npm. Can you still reproduce?
