### ISSUE TITLE
Problems in Android / general rendering issue

### ISSUE THREAD

**Issue by jforaker** [bulenttastan/react-native-list-popover#9]
Straight from example, `this.showPopover` method: 

`Warning: Any use of a keyed object should be wrapped in React.addons.createFragment(object) before being passed as a child.`

And it does not show

**Comment by praisegeek** [comment]
Experienced the same issue.

**Comment by bulenttastan** [comment]
Haven't tested it with android, will look into building for android to replicate the issue.
If you have the solution feel free to send a merge request.

**Comment by shivangbtech** [comment]
List not visible when I click on button

**Comment by 1tilly** [comment]
hey! has anyone found a solution or replacement to avoid this problem??

**Comment by tdhz77** [comment]
I refactored with ES6 and still unable to get list with button visible.

**Comment by jkomyno** [comment]
@tdhz77 same

**Comment by bulenttastan** [comment]
Need to port it to React.Component and refactor the code.
Will do that as part of issue https://github.com/bulenttastan/react-native-list-popover/issues/20
